### ISSUE TITLE
Export utility is inserting quotes into stormpath hrefs

### ISSUE THREAD

**Issue by alavers** [okta/stormpath-migration#52]
Not sure where else to file this issue. I just ran an export of my stormpath data and the account .json files have hrefs that look like this:

```
  "directory" : {
    "href" : "\"https://api.stormpath.com/v1\"/directories/3adFeiMDddo2zDcVZY0XXS"
  }
```

(note the escaped quotes). This breaks the import.

**Comment by mdeggies** [comment]
Thanks for the report, @alavers- we are in the midst of updating the export script, as there was a breaking change made yesterday. I'll let you know as soon as it's ready for use.

**Comment by mdeggies** [comment]
@alavers, please try requesting another export and then re-try the import script. We fixed the problem, and added more test coverage to eliminate the possibility of getting stuck in this situation again.

**Comment by alavers** [comment]
Fix confirmed!
