### ISSUE TITLE
Account Linking fails if more than three links exist for the account 

### ISSUE THREAD

**Issue by saimaddali** [okta/stormpath-migration#56]
If I have an account with three other account links and all have the same email, the tool gets into an infinite loop and throws a heap out of memory error. This isn't fixed by the heap out of memory branch. 

The loop seems to be occurring here: https://github.com/okta/stormpath-migration/blob/master/stormpath/account-links.js#L47-L51

The three accounts belong to different directories and different applications but they share the same email and username.

**Comment by rchild-okta** [comment]
Fixed with https://github.com/okta/stormpath-migration/pull/58
